-- ═══════════════════════════════════════════════════════════════════
-- MAGASIN 2K — Import 95 pièces Iveco (Quick service)
-- Source : Besoin Quick service Iveco PIKE.xlsx (feuille Sheet3)
-- parc = 'iveco' | SANS catégorie ni code RM (à catégoriser ensuite)
-- N'écrase aucun article existant (WHERE NOT EXISTS).
-- ═══════════════════════════════════════════════════════════════════
INSERT INTO articles
  (num, nom, categorie, tags, location, min, max, photo, npf, fournisseur,
   bus_std, bus_art, chimique, reparable, entretien, interne, stock_securite, parc)
SELECT v.num, v.nom, v.categorie, v.tags, v.location, v.min, v.max, v.photo, v.npf, v.fournisseur,
       v.bus_std, v.bus_art, v.chimique, v.reparable, v.entretien, v.interne, v.stock_securite, v.parc
FROM (VALUES
  ('14000017','BATTERIE 12V - 225AH','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000021','F_PARE-CHOC AVG PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000022','F_PARE-CHOC AVD PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000023','F_PARE-CHOCS PLAQUE AV. MILIEU PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000024','F_PARE-CHOCS ARG PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000025','F_PARE-CHOCS ARD PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000026','F_PARE-CHOCS PLAST. AR MILIEU PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000027','F_PARE-CHOCS AV. MILIEU PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000029','GACHE DE PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000031','BOUCHON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000034','F_PLAQUE PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000064','BALAI ESSUIE-GLACE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000065','BRAS ESSUIE-GLACE DROIT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000067','BRAS ESSUIE-GLACE GAUCHE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000071','PHARE DROIT UC','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000072','PHARE GAUCHE UC','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000074','F_ENJOLIVEUR PHARE AVG PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000075','F_ENJOLIVEUR PHARE AVD PEINT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000076','ESSUIE-GLACE MECANISME','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000087','INTERRUPTEUR MICROPHONE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000088','LAMPE 24V 70W','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000090','MICROPHONE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000096','SUPP. MOT. ESSUIE-GLACE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000107','GACHE DE PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000178','SERRURE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000180','SERRURE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000181','PORTE MANTEAU','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000183','SERRURE PORTE OMC COMPLET','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000186','SERRURE PORTE OMC','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000326','BROSSE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000327','BROSSE PORTE ARG','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000328','BROSSE P1','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000329','BROSSE P2','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000384','KIT FIXATION BRAS ESS.-GLACE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000395','PARE-SOLEIL AVANT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000396','PARE-SOLEIL LATERAL','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000458','SERRURE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000639','KIT BOUTON CANNE CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000640','KIT BOUTON CHAISE/LANDEAU CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000641','KIT BOUTON CHAISE/LANDEAU CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000642','KIT BOUTON LANDEAU EXT. CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000643','BOUTON VOYAGEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000771','RETROVISEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000901','BOUTON OUV.PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000913','BOUTON OUV.PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000935','BATTERIE 12V - 105AH','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001260','POIGNEE D''ACCROCHE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001301','MIROIR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001302','MIROIR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001303','KIT-RETROVISEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001305','RETROVISEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001312','BOUTON POUSSOIR ALARME','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001418','BP ROUGE FERMETURE PORTES','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001419','BP BLEU OUVERTURE PORTES','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001447','RETROVISEUR GAUCHE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001450','VIS SIX PANS INT','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001451','VIS','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001452','RONDELLE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001468','FUSIBLE 200A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001475','CHARGE BATTERIE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001476','PROTECTION BATTERIE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001487','BP BLEU OUVERTURE PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001488','PARE SOLEIL','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001636','MIRROIR RETRO. INTERNE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001645','DOSSIER STRAPONTIN 1.5P CUIR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001718','FIXATION MIROIR INT.','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002059','FUSIBLE 3A CLIM.','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002060','FUSIBLE MEGA 400A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002063','FUSIBLE MEGA 25A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002073','FUSIBLE MEGA 125A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002080','FUSIBLE MEGA 150A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002086','FUSIBLE MEGA 350A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002092','FUSIBLE MEGA 40A','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002296','DISPOS DE RETENUE RETROVISEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002374','INTER. AIR CLIM. D2 (Z06.41.110)','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002412','VIS TETE NOYEE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002440','TUBE PORTE / LAVE GLACE 3,5','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002441','JOINT PLAT MOTEUR','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002443','RACCORD ORIENTABLE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002464','RONDELLE BLOQUAGE PORTE','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002472','FUSIBLE S500','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002478','INTER. AIR CLIM. (Z06.41.138) SW02/06','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002495','ACCOUDOIR DROIT SIEGE PASSAGER','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002496','ACCOUDOIR GAUCHE SIEGE PASSAGER','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002501','FUSIBLE 20A MAXI','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002540','BOUTON CANNE CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002541','BOUTON CHAISE CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002542','BOUTON CHAISE/LANDEAU CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002543','BOUTON LANDEAU CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002544','BOUTON MAIN CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002545','CACHE BLEU AV CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002546','CACHE VERT AV CAPTRON','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002548','ELECTRO AIMANT PORTE OMC','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002553','BOUCHON VASE D''EXPANSION','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002554','JOINT BOUCHON VASE D''EXPANSION','','','',0,0,NULL,'','',false,false,false,false,false,false,0,'iveco')
) AS v(num,nom,categorie,tags,location,min,max,photo,npf,fournisseur,bus_std,bus_art,chimique,reparable,entretien,interne,stock_securite,parc)
WHERE NOT EXISTS (SELECT 1 FROM articles a WHERE a.num = v.num);
