-- ═══ MAGASIN 2K — Remplacement catalogue Iveco (v2, gestion pièces communes) ═══
-- DELETE des anciennes Iveco + INSERT des 49 pièces.
-- Une pièce déjà présente en Citaro (num unique) devient 'commun' (visible dans les 2).
-- Re-jouable sans erreur.

DELETE FROM articles WHERE parc = 'iveco';
INSERT INTO articles
  (num, nom, categorie, tags, location, min, max, photo, npf, fournisseur,
   bus_std, bus_art, chimique, reparable, entretien, interne, stock_securite, parc)
VALUES
  ('14000017','BATTERIE 12V - 225AH','','','',2,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000029','GACHE DE PORTE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000031','BOUCHON','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000062','RETROVISEUR DROIT HYBRID','','','',3,4,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000063','RETROVISEUR GAUCHE','','','',3,4,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000064','BALAI ESSUIE-GLACE','','','',7,11,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000077','FEU ARG','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000078','FEU ARD','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000079','FEU AR','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000082','ECLAIRE PLAQUE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000094','PHARE DROIT','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000095','PHARE GAUCHE','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000152','ECLAIRAGE INTERIEUR','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000183','SERRURE PORTE OMC COMPLET','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000348','CLIQUET','','','',2,3,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000375','JOINT DE PORTE','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000396','PARE-SOLEIL LATERAL','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000399','PASSAGE DE ROUE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000458','SERRURE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000633','COMM. REGLAGE RETROVISEUR','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000635','CACHE COLONNE DROIT','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000639','KIT BOUTON CANNE CAPTRON','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000641','KIT BOUTON CHAISE/LANDEAU CAPTRON','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000642','KIT BOUTON LANDEAU EXT. CAPTRON','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000643','BOUTON VOYAGEUR','','','',2,3,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000644','KIT BOUTON MAIN CAPTRON','','','',2,3,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000818','PRE. SELECT. DE VITESSE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000873','INTER.SECOURS BATTERIE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000922','BOUTON POUSSOIR','','','',2,4,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14000935','BATTERIE 12V - 105AH','','','',2,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001033','POIGNEE MAINTIEN','','','',3,5,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001281','POIGNEE MAINTIEN','','','',2,3,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001293','ECROU DE ROUE','','','',20,30,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001312','BOUTON POUSSOIR ALARME','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001396','BOUTON DE DEMARRAGE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001397','CIRCUIT IMPRIME A','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001398','CIRCUIT IMPRIME B','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001414','CMD NAVIGATION TB','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001417','CMD OUVERTURE PORTE MANUEL','','','',3,4,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001454','BOUCHON ADBLUE','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001480','CACHE COLONNE GAUCHE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001487','BP BLEU OUVERTURE PORTE','','','',6,10,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001488','PARE SOLEIL','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001518','COMMODO V2','','','',2,3,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001521','PROFILE BORDURE','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001523','ECLAIRAGE INTERIEUR','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14001636','MIRROIR RETRO. INTERNE','','','',1,2,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002407','ECROU GACHE PORTE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco'),
  ('14002437','BOUCHON CLAPET ADBLUE','','','',1,1,NULL,'','',false,false,false,false,false,false,0,'iveco')
ON CONFLICT (num) DO UPDATE SET parc = 'commun';
